### ISSUE TITLE
Feature request: Support .snyk ignores

### ISSUE THREAD

**Issue by Clete2** [snyk-tech-services/snyk-filter#91]
Can you support .snyk ignores?

My .snyk is:

```yaml
ignore:
  SNYK-JS-ANSIREGEX-1583908:
    - '*':
      reason: 'This dependency is not actually used. See: https://github.com/aws/aws-sdk-js-v3/issues/3640'
      expires: '2024-01-01T00:00:00.000Z'
```

Snyk-filter should honor those ignores.
